version: "2"

services:
  nodejs:
    build: .
    command: nodemon --inspect=0.0.0.0:9222 server.js
    volumes:
      - .:/code
    ports:
      - "8080"
      - "9222:9222"

  ngrok:
    image: wernight/ngrok
    links: 
      - nginx:80
    command: ngrok http nginx:80
    ports:
      - "4040"

  nginx:
    image: nginx
    links:
      - nodejs:8080
    volumes: 
      - ./static:/usr/share/nginx/html:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80"
      - "443"

